version: '3'

networks:
  openhim:

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - openhim
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  openhim-core:
    container_name: openhim-core
    build: 
      context: ./  # Directorio donde se encuentra el Dockerfile
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-development"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-development"
      NODE_ENV: "development"
      api_authenticationTypes: '["token", "basic", "openid", "local"]'
      # Uncomment and set the following variables to enable SSO authentication (openid)
      # api_openid_url: ${KC_FRONTEND_URL}/realms/${KC_REALM_NAME}
      # api_openid_callbackUrl: ${KC_OPENHIM_ROOT_URL}
      # api_openid_clientId: ${KC_OPENHIM_CLIENT_ID}
      # api_openid_clientSecret: ${KC_OPENHIM_CLIENT_SECRET}
      OPENHIM_CONSOLE_PROTOCOL: ${OPENHIM_CONSOLE_PROTOCOL}
      OPENHIM_CORE_MEDIATOR_HOSTNAME: ${OPENHIM_CORE_MEDIATOR_HOSTNAME}
      OPENHIM_CONSOLE_HOSTPATH: ${OPENHIM_CONSOLE_HOSTPATH}
      OPENHIM_MEDIATOR_API_PORT: ${OPENHIM_MEDIATOR_API_PORT}
      OPENHIM_MEDIATOR_HEALTH_WARNING_TIMEOUT: ${OPENHIM_MEDIATOR_HEALTH_WARNING_TIMEOUT}
      OPENHIM_MEDIATOR_HEALTH_DANGER_TIMEOUT: ${OPENHIM_MEDIATOR_HEALTH_DANGER_TIMEOUT}
      OPENHIM_CONSOLE_SHOW_LOGIN: ${OPENHIM_CONSOLE_SHOW_LOGIN}
      KC_OPENHIM_SSO_ENABLED: ${KC_OPENHIM_SSO_ENABLED}
      KC_FRONTEND_URL: ${KC_FRONTEND_URL}
      KC_REALM_NAME: ${KC_REALM_NAME}
      KC_OPENHIM_CLIENT_ID: ${KC_OPENHIM_CLIENT_ID}
    
    ports:
      - "8081:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      - openhim
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
      - openhim
    ports:
      - "9000:80"
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  mongo-data:
